// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    IFluentSettings32Regular: typeof import('~icons/fluent/settings32-regular')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}

export { }
